include build-mk/sources/common.mk

CGAME_C_SOURCES := \
	src/client/cgame/animation/anim_tree_load.c \
	src/client/cgame/animation/cg_buildcorpsedobjmodels.c \
	src/client/cgame/animation/cg_calcentitylerppositions.c \
	src/client/cgame/animation/cg_createmg42weaponanimtree.c \
	src/client/cgame/animation/cg_dobjcalcbone.c \
	src/client/cgame/animation/cg_dobjcalcbonegeneric.c \
	src/client/cgame/animation/cg_dobjcalcpose.c \
	src/client/cgame/animation/cg_dobjgetboneboundswireframe.c \
	src/client/cgame/animation/cg_dobjgetentitybonematrix.c \
	src/client/cgame/animation/cg_dobjgetspecialtagworldmatrix.c \
	src/client/cgame/animation/cg_dobjgetworldboneboundswireframe.c \
	src/client/cgame/animation/cg_dobjgetworldtagmatrix.c \
	src/client/cgame/animation/cg_dobjsetcontroltagangles.c \
	src/client/cgame/animation/cg_dobjsetlocaltag.c \
	src/client/cgame/animation/cg_dobjsetlocaltaginternal.c \
	src/client/cgame/animation/cg_docontrollers.c \
	src/client/cgame/animation/cg_freeregisteredhandleshigh.c \
	src/client/cgame/animation/cg_freeregisteredhandleslow.c \
	src/client/cgame/animation/cg_interpolateentityposition.c \
	src/client/cgame/animation/cg_mg42_docontrollers.c \
	src/client/cgame/animation/cg_player_docontrollers.c \
	src/client/cgame/animation/cg_refreshentitydobjanimtree.c \
	src/client/cgame/animation/cg_trajectorypointinbounds.c \
	src/client/cgame/animation/constrainvectortowardforward.c \
	src/client/cgame/bg/bg_parseweaponinfofiles.c \
	src/client/cgame/bg/cg_allocweaponinfo.c \
	src/client/cgame/bg/cg_copystring.c \
	src/client/cgame/bg/cg_weaponinfosetstring.c \
	src/client/cgame/bg/initweaponinfo.c \
	src/client/cgame/common/math_inline.c \
	src/client/cgame/common/parse_string_leaves.c \
	src/client/cgame/common/q_stripcontrol0x19.c \
	src/client/cgame/common/q_striptoalphanumeric.c \
	src/client/cgame/common/sort_strings.c \
	src/client/cgame/effects/cg_addcamerashake.c \
	src/client/cgame/effects/cg_addfadergb.c \
	src/client/cgame/effects/cg_addflamechunks.c \
	src/client/cgame/effects/cg_addflametoscene.c \
	src/client/cgame/effects/cg_addlocalentities.c \
	src/client/cgame/effects/cg_addmarks.c \
	src/client/cgame/effects/cg_addmovingtracer.c \
	src/client/cgame/effects/cg_addscalefade.c \
	src/client/cgame/effects/cg_advanceflamechunksize.c \
	src/client/cgame/effects/cg_alloclocalentity.c \
	src/client/cgame/effects/cg_allocmark.c \
	src/client/cgame/effects/cg_calcviewshake.c \
	src/client/cgame/effects/cg_clearflamechunks.c \
	src/client/cgame/effects/cg_computeflamechunkorigin.c \
	src/client/cgame/effects/cg_debugbox.c \
	src/client/cgame/effects/cg_debugcircle.c \
	src/client/cgame/effects/cg_debugcircleex.c \
	src/client/cgame/effects/cg_emitplayerflamechunks.c \
	src/client/cgame/effects/cg_endshellshock.c \
	src/client/cgame/effects/cg_endshellshockmouse.c \
	src/client/cgame/effects/cg_endshellshocksound.c \
	src/client/cgame/effects/cg_evaluatecamerashakesource.c \
	src/client/cgame/effects/cg_fireflamechunks.c \
	src/client/cgame/effects/cg_flamedamage.c \
	src/client/cgame/effects/cg_flamedropdrip.c \
	src/client/cgame/effects/cg_flamegetsizerate.c \
	src/client/cgame/effects/cg_flamethrowertrace.c \
	src/client/cgame/effects/cg_freeflamechunk.c \
	src/client/cgame/effects/cg_fxrestart.c \
	src/client/cgame/effects/cg_fxsettestposition.c \
	src/client/cgame/effects/cg_fxtest.c \
	src/client/cgame/effects/cg_impactmark.c \
	src/client/cgame/effects/cg_initflamechunks.c \
	src/client/cgame/effects/cg_initlocalentities.c \
	src/client/cgame/effects/cg_initmarkpolys.c \
	src/client/cgame/effects/cg_mergeflamechunks.c \
	src/client/cgame/effects/cg_moveflamechunk.c \
	src/client/cgame/effects/cg_parseimpacteffects.c \
	src/client/cgame/effects/cg_playfx.c \
	src/client/cgame/effects/cg_playfxontag.c \
	src/client/cgame/effects/cg_playspinningvieweffect.c \
	src/client/cgame/effects/cg_poissondisksample.c \
	src/client/cgame/effects/cg_printpoissondisksamples.c \
	src/client/cgame/effects/cg_registereffectdefsurfaces.c \
	src/client/cgame/effects/cg_registerimpacteffects.c \
	src/client/cgame/effects/cg_sendflamedamagecommand.c \
	src/client/cgame/effects/cg_setshellshockparams.c \
	src/client/cgame/effects/cg_shellshockcalcvibrate.c \
	src/client/cgame/effects/cg_shellshockload.c \
	src/client/cgame/effects/cg_shellshocksave.c \
	src/client/cgame/effects/cg_spawnflamechunk.c \
	src/client/cgame/effects/cg_spawnflamechunkonbone.c \
	src/client/cgame/effects/cg_startflamedamageeffect.c \
	src/client/cgame/effects/cg_updatefadeoverlay.c \
	src/client/cgame/effects/cg_updateflamechunk.c \
	src/client/cgame/effects/cg_updateflamethrowersounds.c \
	src/client/cgame/effects/cg_updateperiodiceffect.c \
	src/client/cgame/effects/cg_updateshellshock.c \
	src/client/cgame/effects/cg_updateshellshockcamera.c \
	src/client/cgame/effects/cg_updateshellshockmouse.c \
	src/client/cgame/effects/cg_updateshellshocksound.c \
	src/client/cgame/effects/cg_writeflameshaderfile.c \
	src/client/cgame/entities/add_centity.c \
	src/client/cgame/entities/cg_addcentity_loopedfx.c \
	src/client/cgame/entities/cg_addheadicon.c \
	src/client/cgame/entities/cg_addheadiconsprite.c \
	src/client/cgame/entities/cg_addlightningbeam.c \
	src/client/cgame/entities/cg_addpacketentities.c \
	src/client/cgame/entities/cg_addplayerwatershadow.c \
	src/client/cgame/entities/cg_adjustpositionformover.c \
	src/client/cgame/entities/cg_checkevents.c \
	src/client/cgame/entities/cg_checkpreevents.c \
	src/client/cgame/entities/cg_entityevent.c \
	src/client/cgame/entities/cg_entitypreevent.c \
	src/client/cgame/entities/cg_missile.c \
	src/client/cgame/entities/cg_mover.c \
	src/client/cgame/entities/cg_playershadow.c \
	src/client/cgame/entities/cg_portal.c \
	src/client/cgame/entities/cg_resetplayerentity.c \
	src/client/cgame/entities/cg_scriptmover.c \
	src/client/cgame/entities/cg_setframeinterpolation.c \
	src/client/cgame/entities/cg_setgunhandfromnotetracks.c \
	src/client/cgame/entities/cg_updateplayerdobj.c \
	src/client/cgame/entities/entity_effects.c \
	src/client/cgame/entities/general_entity.c \
	src/client/cgame/entities/item_entity.c \
	src/client/cgame/entities/looped_sound_entity.c \
	src/client/cgame/entities/player_corpse_entity.c \
	src/client/cgame/entities/player_entity.c \
	src/client/cgame/entities/turret_entity.c \
	src/client/cgame/functions/recovered_cgame_ui_state_leaves.c \
	src/client/cgame/functions/recovered_dobj_effect_state_leaves.c \
	src/client/cgame/functions/recovered_empty_callbacks.c \
	src/client/cgame/functions/recovered_math_transform_leaves.c \
	src/client/cgame/functions/recovered_medium_leaves.c \
	src/client/cgame/functions/recovered_misc_tiny_leaves.c \
	src/client/cgame/functions/recovered_parser_anim_predicates.c \
	src/client/cgame/functions/recovered_small_accessors.c \
	src/client/cgame/functions/recovered_small_dispatch_helpers.c \
	src/client/cgame/functions/recovered_small_forwarders.c \
	src/client/cgame/functions/recovered_small_math_state_leaves.c \
	src/client/cgame/functions/recovered_tiny_routing_leaves.c \
	src/client/cgame/functions/recovered_weapon_score_cvar_leaves.c \
	src/client/cgame/globals.c \
	src/client/cgame/hud/center_string.c \
	src/client/cgame/hud/cg_addlagometersnapshotinfo.c \
	src/client/cgame/hud/cg_calcadsoverlayfrac.c \
	src/client/cgame/hud/cg_checkammo.c \
	src/client/cgame/hud/cg_configstring11modified.c \
	src/client/cgame/hud/cg_consolidatehudelemtext.c \
	src/client/cgame/hud/cg_damagefeedback.c \
	src/client/cgame/hud/cg_draw1stplace.c \
	src/client/cgame/hud/cg_draw2d.c \
	src/client/cgame/hud/cg_draw2ndplace.c \
	src/client/cgame/hud/cg_drawactive.c \
	src/client/cgame/hud/cg_drawareachat.c \
	src/client/cgame/hud/cg_drawareasystemchat.c \
	src/client/cgame/hud/cg_drawareateamchat.c \
	src/client/cgame/hud/cg_drawbluescore.c \
	src/client/cgame/hud/cg_drawclientscore.c \
	src/client/cgame/hud/cg_drawcompassfriendlies.c \
	src/client/cgame/hud/cg_drawcompasstanks.c \
	src/client/cgame/hud/cg_drawcrosshair.c \
	src/client/cgame/hud/cg_drawcrosshairnames.c \
	src/client/cgame/hud/cg_drawcursorhint.c \
	src/client/cgame/hud/cg_drawdamagedirectionindicators.c \
	src/client/cgame/hud/cg_drawdebugfadeelement.c \
	src/client/cgame/hud/cg_drawdebugoverlays.c \
	src/client/cgame/hud/cg_drawdisconnect.c \
	src/client/cgame/hud/cg_drawfield.c \
	src/client/cgame/hud/cg_drawfieldwidth.c \
	src/client/cgame/hud/cg_drawfilledbarstyled.c \
	src/client/cgame/hud/cg_drawfixedfadeelement.c \
	src/client/cgame/hud/cg_drawflashdamage.c \
	src/client/cgame/hud/cg_drawfps.c \
	src/client/cgame/hud/cg_drawgametype.c \
	src/client/cgame/hud/cg_drawhudelemclock.c \
	src/client/cgame/hud/cg_drawhudelems.c \
	src/client/cgame/hud/cg_drawhudelemshader.c \
	src/client/cgame/hud/cg_drawhudelemstring.c \
	src/client/cgame/hud/cg_drawhudslidepiccolor.c \
	src/client/cgame/hud/cg_drawinformation.c \
	src/client/cgame/hud/cg_drawintermission.c \
	src/client/cgame/hud/cg_drawjeepbody.c \
	src/client/cgame/hud/cg_drawmatchtimeout.c \
	src/client/cgame/hud/cg_drawobituaryline.c \
	src/client/cgame/hud/cg_drawobjectiveinfo.c \
	src/client/cgame/hud/cg_drawobjectivepointers.c \
	src/client/cgame/hud/cg_drawpic.c \
	src/client/cgame/hud/cg_drawplayerammobackdrop.c \
	src/client/cgame/hud/cg_drawplayerammovalue.c \
	src/client/cgame/hud/cg_drawplayerbarhealthtitle.c \
	src/client/cgame/hud/cg_drawplayerlocation.c \
	src/client/cgame/hud/cg_drawplayerstance.c \
	src/client/cgame/hud/cg_drawplayerweaponmodeicon.c \
	src/client/cgame/hud/cg_drawplayerweaponname.c \
	src/client/cgame/hud/cg_drawplayerweaponnameback.c \
	src/client/cgame/hud/cg_drawrect.c \
	src/client/cgame/hud/cg_drawredscore.c \
	src/client/cgame/hud/cg_drawrotatedpic.c \
	src/client/cgame/hud/cg_drawrotatedquadpic.c \
	src/client/cgame/hud/cg_drawscoreboard_getteamcolor.c \
	src/client/cgame/hud/cg_drawscoreboard_listbanner.c \
	src/client/cgame/hud/cg_drawscoreboard_listcolumnheaders.c \
	src/client/cgame/hud/cg_drawscoreboard_scoreslist.c \
	src/client/cgame/hud/cg_drawscoreboard_scrollindicators.c \
	src/client/cgame/hud/cg_drawscoreboard.c \
	src/client/cgame/hud/cg_drawscoreboardbody.c \
	src/client/cgame/hud/cg_drawscoreboardfadeelement.c \
	src/client/cgame/hud/cg_drawscoreboardteamheader.c \
	src/client/cgame/hud/cg_drawscriptusage.c \
	src/client/cgame/hud/cg_drawselectedplayerlocation.c \
	src/client/cgame/hud/cg_drawselectedplayername.c \
	src/client/cgame/hud/cg_drawsides.c \
	src/client/cgame/hud/cg_drawsinglehudelem.c \
	src/client/cgame/hud/cg_drawslidingfadeelement.c \
	src/client/cgame/hud/cg_drawsoundoverlay.c \
	src/client/cgame/hud/cg_drawspectatormessage.c \
	src/client/cgame/hud/cg_drawspinningpic.c \
	src/client/cgame/hud/cg_drawstatbarwithdecay.c \
	src/client/cgame/hud/cg_drawstretchpic.c \
	src/client/cgame/hud/cg_drawstretchpiccolor.c \
	src/client/cgame/hud/cg_drawtankbarrel.c \
	src/client/cgame/hud/cg_drawtankbody.c \
	src/client/cgame/hud/cg_drawtankpositionstatus.c \
	src/client/cgame/hud/cg_drawteambackground.c \
	src/client/cgame/hud/cg_drawteaminfo.c \
	src/client/cgame/hud/cg_drawtopbottom.c \
	src/client/cgame/hud/cg_drawturrettagquad.c \
	src/client/cgame/hud/cg_drawvote.c \
	src/client/cgame/hud/cg_drawweaponicon3d.c \
	src/client/cgame/hud/cg_drawweapreticle.c \
	src/client/cgame/hud/cg_emitlocalteambackground.c \
	src/client/cgame/hud/cg_emittrap54drawscaled.c \
	src/client/cgame/hud/cg_fadecolor.c \
	src/client/cgame/hud/cg_filledbar.c \
	src/client/cgame/hud/cg_fillrect.c \
	src/client/cgame/hud/cg_gethudeleminfo.c \
	src/client/cgame/hud/cg_gethudelemtime.c \
	src/client/cgame/hud/cg_getobjectiveshaderfordir.c \
	src/client/cgame/hud/cg_getshaderconfigstring.c \
	src/client/cgame/hud/cg_getsortedhudelems.c \
	src/client/cgame/hud/cg_gettranslatedlocationstring.c \
	src/client/cgame/hud/cg_hudelemheight.c \
	src/client/cgame/hud/cg_hudelemshaderheight.c \
	src/client/cgame/hud/cg_hudelemshaderwidth.c \
	src/client/cgame/hud/cg_hudelemstringwidth.c \
	src/client/cgame/hud/cg_hudelemtenthstimerstring.c \
	src/client/cgame/hud/cg_hudelemtimerstring.c \
	src/client/cgame/hud/cg_hudelemwidth.c \
	src/client/cgame/hud/cg_hudelemx.c \
	src/client/cgame/hud/cg_hudelemy.c \
	src/client/cgame/hud/cg_hudemitdigits.c \
	src/client/cgame/hud/cg_hudemiticonorvalue.c \
	src/client/cgame/hud/cg_latchoverlaysource.c \
	src/client/cgame/hud/cg_obituary.c \
	src/client/cgame/hud/cg_ownerdraw.c \
	src/client/cgame/hud/cg_ownerdrawvalue.c \
	src/client/cgame/hud/cg_prioritycenterprint.c \
	src/client/cgame/hud/cg_projectdamagedirtoscreen.c \
	src/client/cgame/hud/cg_registerscoreboardshaders.c \
	src/client/cgame/hud/cg_scanforcrosshairentity.c \
	src/client/cgame/hud/cg_scoreboardheight.c \
	src/client/cgame/hud/cg_scrollscoreboarddown.c \
	src/client/cgame/hud/cg_startfovfade.c \
	src/client/cgame/hud/cg_tileclear.c \
	src/client/cgame/hud/cg_tileclearbox.c \
	src/client/cgame/hud/cg_trap54drawstyle4.c \
	src/client/cgame/hud/cg_trap54drawstyle5.c \
	src/client/cgame/hud/cg_updatecompassorientation.c \
	src/client/cgame/hud/cg_updatehudspinangle.c \
	src/client/cgame/hud/cg_updatescreenfade.c \
	src/client/cgame/hud/cg_voicemenutimeout.c \
	src/client/cgame/hud/draw_big_string.c \
	src/client/cgame/hud/draw_small_string.c \
	src/client/cgame/hud/expiring_icons.c \
	src/client/cgame/hud/following_message.c \
	src/client/cgame/hud/hudelemsortcompare.c \
	src/client/cgame/hud/info_screens.c \
	src/client/cgame/hud/lagometer.c \
	src/client/cgame/hud/routehudstring.c \
	src/client/cgame/hud/screen_fade.c \
	src/client/cgame/hud/snapshot_debug.c \
	src/client/cgame/hud/spectator_follow_hints.c \
	src/client/cgame/hud/view_info.c \
	src/client/cgame/module/cg_argv.c \
	src/client/cgame/module/cg_boldgamemessage.c \
	src/client/cgame/module/cg_consolecommand.c \
	src/client/cgame/module/cg_crosshairplayer.c \
	src/client/cgame/module/cg_fade_f.c \
	src/client/cgame/module/cg_gamemessage.c \
	src/client/cgame/module/cg_geteffectoriginaxis.c \
	src/client/cgame/module/cg_getentityoriginaxis.c \
	src/client/cgame/module/cg_init.c \
	src/client/cgame/module/cg_initconsolecommands.c \
	src/client/cgame/module/cg_printvieworiginandspin_f.c \
	src/client/cgame/module/cg_registercvars.c \
	src/client/cgame/module/cg_registermaterial.c \
	src/client/cgame/module/cg_registermodel.c \
	src/client/cgame/module/cg_shellshock_f.c \
	src/client/cgame/module/cg_shellshock_load_f.c \
	src/client/cgame/module/cg_shutdowneffectsandhud.c \
	src/client/cgame/module/cg_voicechat_f.c \
	src/client/cgame/module/cgame_entry.c \
	src/client/cgame/module/cgame_imports.c \
	src/client/cgame/module/cgame_vm_main.c \
	src/client/cgame/module/com_dprintf.c \
	src/client/cgame/module/com_error.c \
	src/client/cgame/module/com_errormessage.c \
	src/client/cgame/module/com_printf.c \
	src/client/cgame/module/com_printmessage.c \
	src/client/cgame/module/console_command_leaves.c \
	src/client/cgame/module/trap_com_picksoundalias.c \
	src/client/cgame/module/trap_com_soundaliasstring.c \
	src/client/cgame/module/trap_cvar_set.c \
	src/client/cgame/module/trap_datetimestamp.c \
	src/client/cgame/module/trap_fx_adjusttime.c \
	src/client/cgame/module/trap_fx_setwind.c \
	src/client/cgame/module/trap_mss_playblendedsoundaliases.c \
	src/client/cgame/module/trap_mss_playsoundalias.c \
	src/client/cgame/module/trap_r_addlighttoscene.c \
	src/client/cgame/module/trap_r_drawquadpic.c \
	src/client/cgame/module/trap_r_drawstretchpic.c \
	src/client/cgame/module/trap_r_registerfont.c \
	src/client/cgame/module/trap_r_registershadernomip.c \
	src/client/cgame/module/trap_r_setcolor.c \
	src/client/cgame/module/trap_r_setfog.c \
	src/client/cgame/module/trap_r_text_height.c \
	src/client/cgame/module/trap_r_text_paint_with_cursor.c \
	src/client/cgame/module/trap_r_text_paint.c \
	src/client/cgame/module/trap_r_text_width.c \
	src/client/cgame/module/trap_xanimcleartreegoalweightsstrict.c \
	src/client/cgame/module/trap_xanimgetanimname.c \
	src/client/cgame/module/trap_xanimgetchildat.c \
	src/client/cgame/module/trap_xanimgetnumchildren.c \
	src/client/cgame/module/trap_xanimgettime.c \
	src/client/cgame/module/trap_xanimgetweight.c \
	src/client/cgame/module/trap_xanimislooped.c \
	src/client/cgame/module/trap_xanimsetcompletegoalweight.c \
	src/client/cgame/module/trap_xanimsetcompletegoalweightknoball.c \
	src/client/cgame/module/trap_xanimsetgoalweight.c \
	src/client/cgame/module/ui_display_context_traps.c \
	src/client/cgame/platform/native_ui_callback_adapters.c \
	src/client/cgame/prediction/cg_buildsolidlist.c \
	src/client/cgame/prediction/cg_clipmovetoentities.c \
	src/client/cgame/prediction/cg_getridertagname.c \
	src/client/cgame/prediction/cg_interpolateplayerstate.c \
	src/client/cgame/prediction/cg_pointcontents.c \
	src/client/cgame/prediction/cg_predictplayerstate_internal.c \
	src/client/cgame/prediction/cg_predictplayerstate.c \
	src/client/cgame/prediction/cg_touchitem.c \
	src/client/cgame/prediction/cg_touchtriggerprediction.c \
	src/client/cgame/prediction/cg_trace.c \
	src/client/cgame/prediction/cg_tracecapsule.c \
	src/client/cgame/render/cg_buildlockedviewrefdef.c \
	src/client/cgame/render/cg_calcfov.c \
	src/client/cgame/render/cg_calcviewprojection.c \
	src/client/cgame/render/cg_calcviewvalues.c \
	src/client/cgame/render/cg_calcvrect.c \
	src/client/cgame/render/cg_drawactiveframe.c \
	src/client/cgame/render/cg_drawskyboxportal.c \
	src/client/cgame/render/cg_flareinviewcone.c \
	src/client/cgame/render/cg_offsetfirstpersonview.c \
	src/client/cgame/render/cg_offsetthirdpersonview.c \
	src/client/cgame/render/cg_registergraphics.c \
	src/client/cgame/render/cg_registersurfacetypesounds.c \
	src/client/cgame/render/cg_settlevieworiginz.c \
	src/client/cgame/render/cg_setupweaponlightingorigin.c \
	src/client/cgame/render/cg_updateviewkick.c \
	src/client/cgame/render/cgame_compat_presentation.c \
	src/client/cgame/sound/cg_findvoicechatfileindex.c \
	src/client/cgame/sound/cg_gettranslatedvoicechatstring.c \
	src/client/cgame/sound/cg_loadvoicechats.c \
	src/client/cgame/sound/cg_localsound_f.c \
	src/client/cgame/sound/cg_localsound.c \
	src/client/cgame/sound/cg_parsevoicechat.c \
	src/client/cgame/sound/cg_parsevoicechats.c \
	src/client/cgame/sound/cg_picksoundalias.c \
	src/client/cgame/sound/cg_playclientsoundaliasbyname.c \
	src/client/cgame/sound/cg_playentitysoundaliasbyname.c \
	src/client/cgame/sound/cg_playgearrattlesound.c \
	src/client/cgame/sound/cg_playsoundaliasbyname.c \
	src/client/cgame/sound/cg_playvoicechat.c \
	src/client/cgame/sound/cg_registersounds.c \
	src/client/cgame/sound/cg_reverbcmd.c \
	src/client/cgame/sound/cg_voicechat.c \
	src/client/cgame/state/cg_addtoteamchat.c \
	src/client/cgame/state/cg_checkchangedpredictableevents.c \
	src/client/cgame/state/cg_checkplayerstateevents.c \
	src/client/cgame/state/cg_configstring.c \
	src/client/cgame/state/cg_configstring3modified.c \
	src/client/cgame/state/cg_configstringmodified.c \
	src/client/cgame/state/cg_executenewservercommands.c \
	src/client/cgame/state/cg_installsnapshotreseteffects.c \
	src/client/cgame/state/cg_maprestart.c \
	src/client/cgame/state/cg_parsefog.c \
	src/client/cgame/state/cg_parsescores.c \
	src/client/cgame/state/cg_parseserverinfo.c \
	src/client/cgame/state/cg_processsnapshots.c \
	src/client/cgame/state/cg_readnextsnapshot.c \
	src/client/cgame/state/cg_registerconfigstringassets.c \
	src/client/cgame/state/cg_registerconfigstringmenu.c \
	src/client/cgame/state/cg_registerconfigstringshader.c \
	src/client/cgame/state/cg_servercommand.c \
	src/client/cgame/state/cg_setconfigvalues.c \
	src/client/cgame/state/cg_setnextsnap.c \
	src/client/cgame/state/cg_snapshottransitionstage2.c \
	src/client/cgame/state/cg_transitionentity.c \
	src/client/cgame/state/cg_transitionplayerstate.c \
	src/client/cgame/state/cg_transitionsnapshot.c \
	src/client/cgame/ui/binding_services.c \
	src/client/cgame/ui/cg_asset_parse.c \
	src/client/cgame/ui/cg_buildtimeouthudstrings.c \
	src/client/cgame/ui/cg_buildvotehudstrings.c \
	src/client/cgame/ui/cg_checkopenwaitingscriptmenu.c \
	src/client/cgame/ui/cg_closescriptmenu.c \
	src/client/cgame/ui/cg_keyevent.c \
	src/client/cgame/ui/cg_load_menu.c \
	src/client/cgame/ui/cg_loadmenus.c \
	src/client/cgame/ui/cg_openscriptmenu.c \
	src/client/cgame/ui/cg_openvoicemenu.c \
	src/client/cgame/ui/cg_parsemenu.c \
	src/client/cgame/ui/cg_registermenuassets.c \
	src/client/cgame/ui/cg_safetranslatehudelemstring.c \
	src/client/cgame/ui/cg_safetranslatestring_internal.c \
	src/client/cgame/ui/cg_translatemessage.c \
	src/client/cgame/ui/cg_uidisplaycontextinit.c \
	src/client/cgame/ui/cgame_callbacks.c \
	src/client/cgame/ui/cgame_service_callbacks.c \
	src/client/cgame/ui/listbox_services.c \
	src/client/cgame/ui/math_pool_helpers.c \
	src/client/cgame/ui/menu_paint_services.c \
	src/client/cgame/ui/menuparse_visible.c \
	src/client/cgame/ui/script_fadein.c \
	src/client/cgame/vehicles/cg_addcentity_vehicle.c \
	src/client/cgame/vehicles/cg_addhudheadiconsprite.c \
	src/client/cgame/vehicles/cg_calcturretviewvalues.c \
	src/client/cgame/vehicles/cg_calcvehicleviewpos.c \
	src/client/cgame/vehicles/cg_calcvehicleviewvalues.c \
	src/client/cgame/vehicles/cg_getvehicleviewposorigintag.c \
	src/client/cgame/vehicles/cg_playerturretpositionandblend.c \
	src/client/cgame/vehicles/cg_playervehiclepositionandblend.c \
	src/client/cgame/vehicles/cg_vehicle_docontrollers.c \
	src/client/cgame/vehicles/cg_vehicleownericon.c \
	src/client/cgame/weapons/cg_addplayerweapon.c \
	src/client/cgame/weapons/cg_addviewweapon.c \
	src/client/cgame/weapons/cg_applyweaponmovementangles.c \
	src/client/cgame/weapons/cg_bullethitevent.c \
	src/client/cgame/weapons/cg_calcadsviewoffset.c \
	src/client/cgame/weapons/cg_calcmuzzlepoint.c \
	src/client/cgame/weapons/cg_calcviewleankickoffset.c \
	src/client/cgame/weapons/cg_calcweaponmovementangles.c \
	src/client/cgame/weapons/cg_cycleweap.c \
	src/client/cgame/weapons/cg_drawmovingtracerpoly.c \
	src/client/cgame/weapons/cg_drawweaponselect.c \
	src/client/cgame/weapons/cg_drawweaponselectkeyhint.c \
	src/client/cgame/weapons/cg_ejectweaponbrass.c \
	src/client/cgame/weapons/cg_faketrajectoryeffects.c \
	src/client/cgame/weapons/cg_fireweapon.c \
	src/client/cgame/weapons/cg_freeweapondobjhandles.c \
	src/client/cgame/weapons/cg_isweaponheld.c \
	src/client/cgame/weapons/cg_modeleventfireweapon.c \
	src/client/cgame/weapons/cg_outofammochange.c \
	src/client/cgame/weapons/cg_perturbcamera.c \
	src/client/cgame/weapons/cg_playadsanim.c \
	src/client/cgame/weapons/cg_playfxonweapontag.c \
	src/client/cgame/weapons/cg_processweaponnotetracks.c \
	src/client/cgame/weapons/cg_railtrail.c \
	src/client/cgame/weapons/cg_refreshweapondobjmodelset.c \
	src/client/cgame/weapons/cg_refreshweaponinfosforconfigstring.c \
	src/client/cgame/weapons/cg_registeritems.c \
	src/client/cgame/weapons/cg_registeritemvisuals.c \
	src/client/cgame/weapons/cg_registerweapon.c \
	src/client/cgame/weapons/cg_resetweaponanimtrees.c \
	src/client/cgame/weapons/cg_selectfirstweaponinslot.c \
	src/client/cgame/weapons/cg_selectfirstweaponnotinslot.c \
	src/client/cgame/weapons/cg_selectweaponindex.c \
	src/client/cgame/weapons/cg_setselectedweapon.c \
	src/client/cgame/weapons/cg_spawnmovingtracer.c \
	src/client/cgame/weapons/cg_spawnrailcoresegment.c \
	src/client/cgame/weapons/cg_spawnscalefadesprite.c \
	src/client/cgame/weapons/cg_spawntracer.c \
	src/client/cgame/weapons/cg_spawntracerline.c \
	src/client/cgame/weapons/cg_spineffectpointtoworld.c \
	src/client/cgame/weapons/cg_startweaponanim.c \
	src/client/cgame/weapons/cg_stopallweaponanims.c \
	src/client/cgame/weapons/cg_trackadszoomdirection.c \
	src/client/cgame/weapons/cg_weapondobjhandle.c \
	src/client/cgame/weapons/cg_weaponrunxmodelanims.c \
	src/client/cgame/weapons/cg_weaponsway_applyshellshock.c \
	src/client/cgame/weapons/cg_weaponupdateloopingsound.c \
	src/client/cgame/weapons/cg_whizbysound.c \
	src/client/cgame/weapons/console_commands.c
