include build-mk/sources/common.mk

UI_C_SOURCES := \
	src/client/ui/abi/passfloat.c \
	src/client/ui/abi/ui_display_imports.c \
	src/client/ui/abi/ui_syscalls.c \
	src/client/ui/browser/ui_add_server_to_favorites.c \
	src/client/ui/browser/ui_build_server_display_list.c \
	src/client/ui/browser/ui_clear_displayed_servers.c \
	src/client/ui/browser/ui_display_server_list.c \
	src/client/ui/browser/ui_pending_pings.c \
	src/client/ui/browser/ui_server_refresh_start.c \
	src/client/ui/browser/ui_server_refresh_stop.c \
	src/client/ui/browser/ui_server_refresh.c \
	src/client/ui/browser/ui_servers_sort.c \
	src/client/ui/browser/ui_sync_server_list_selection.c \
	src/client/ui/browser/ui_update_display_servers.c \
	src/client/ui/common/com_dprintf.c \
	src/client/ui/common/com_print.c \
	src/client/ui/common/q_math.c \
	src/client/ui/common/random_geometry.c \
	src/client/ui/common/stristr.c \
	src/client/ui/common/temp_runtime_compat.c \
	src/client/ui/common/ui_adjust_from_640.c \
	src/client/ui/common/ui_config_string.c \
	src/client/ui/common/ui_cvar_variable_string.c \
	src/client/ui/common/ui_file_text.c \
	src/client/ui/common/ui_load_arenas_from_file.c \
	src/client/ui/common/ui_load_arenas.c \
	src/client/ui/common/ui_load_menu_text_file.c \
	src/client/ui/common/ui_parse_infos.c \
	src/client/ui/input/control_bindings.c \
	src/client/ui/input/ui_check_exec_key.c \
	src/client/ui/input/ui_game_type_handle_key.c \
	src/client/ui/input/ui_handicap_handle_key.c \
	src/client/ui/input/ui_join_game_type_handle_key.c \
	src/client/ui/input/ui_net_filter_handle_key.c \
	src/client/ui/input/ui_net_game_type_handle_key.c \
	src/client/ui/input/ui_net_source_handle_key.c \
	src/client/ui/input/ui_owner_draw_handle_key.c \
	src/client/ui/localization/ui_safe_translate.c \
	src/client/ui/memory/ui_memory_compat.c \
	src/client/ui/memory/ui_memory_storage.c \
	src/client/ui/memory/ui_report.c \
	src/client/ui/menu/asset_parse.c \
	src/client/ui/menu/display_dispatch.c \
	src/client/ui/menu/item_paint_services.c \
	src/client/ui/menu/load_menu.c \
	src/client/ui/menu/load_script_menu.c \
	src/client/ui/menu/menu_count.c \
	src/client/ui/menu/menu_named_item_mutation.c \
	src/client/ui/menu/menu_paint_services.c \
	src/client/ui/menu/menu_parse_visible.c \
	src/client/ui/menu/script_fade.c \
	src/client/ui/menu/ui_cache.c \
	src/client/ui/menu/ui_get_font_info.c \
	src/client/ui/menu/ui_load_menus.c \
	src/client/ui/menu/ui_load.c \
	src/client/ui/menu/ui_parse_menu.c \
	src/client/ui/module/ui_console.c \
	src/client/ui/module/ui_draw_connect_screen.c \
	src/client/ui/module/ui_empty_callback_400079c0.c \
	src/client/ui/module/ui_entry.c \
	src/client/ui/module/ui_globals.c \
	src/client/ui/module/ui_init.c \
	src/client/ui/module/ui_input.c \
	src/client/ui/module/ui_key_event.c \
	src/client/ui/module/ui_lifecycle.c \
	src/client/ui/module/ui_pause.c \
	src/client/ui/module/ui_postgame.c \
	src/client/ui/module/ui_refresh.c \
	src/client/ui/module/ui_set_active_menu.c \
	src/client/ui/module/ui_test.c \
	src/client/ui/module/ui_vm_main.c \
	src/client/ui/platform/ui_windows_display.c \
	src/client/ui/render/text_font_selection.c \
	src/client/ui/render/text_paint_center.c \
	src/client/ui/render/ui_asset_cache.c \
	src/client/ui/render/ui_cinematic.c \
	src/client/ui/render/ui_cursor_in_rect.c \
	src/client/ui/render/ui_draw_centered_pic.c \
	src/client/ui/render/ui_draw_handle_pic.c \
	src/client/ui/render/ui_draw_named_pic.c \
	src/client/ui/render/ui_rect_primitives.c \
	src/client/ui/state/ui_build_find_player_list.c \
	src/client/ui/state/ui_build_player_list.c \
	src/client/ui/state/ui_build_server_status.c \
	src/client/ui/state/ui_cvars.c \
	src/client/ui/state/ui_display_download_info.c \
	src/client/ui/state/ui_display_names.c \
	src/client/ui/state/ui_download_format.c \
	src/client/ui/state/ui_draw_game_type.c \
	src/client/ui/state/ui_draw_gl_info.c \
	src/client/ui/state/ui_draw_handicap.c \
	src/client/ui/state/ui_draw_join_game_type.c \
	src/client/ui/state/ui_draw_key_bind_status.c \
	src/client/ui/state/ui_draw_map_preview.c \
	src/client/ui/state/ui_draw_net_filter.c \
	src/client/ui/state/ui_draw_net_game_type.c \
	src/client/ui/state/ui_draw_net_map_cinematic.c \
	src/client/ui/state/ui_draw_net_map_preview.c \
	src/client/ui/state/ui_draw_net_source.c \
	src/client/ui/state/ui_draw_preview_cinematic.c \
	src/client/ui/state/ui_draw_server_refresh_date.c \
	src/client/ui/state/ui_draw_server_refresh_totals.c \
	src/client/ui/state/ui_empty_callbacks.c \
	src/client/ui/state/ui_feeder_count.c \
	src/client/ui/state/ui_feeder_item_image.c \
	src/client/ui/state/ui_feeder_item_text.c \
	src/client/ui/state/ui_feeder_selection.c \
	src/client/ui/state/ui_get_game_types_list.c \
	src/client/ui/state/ui_get_server_status_info.c \
	src/client/ui/state/ui_get_value.c \
	src/client/ui/state/ui_load_demos.c \
	src/client/ui/state/ui_load_mods.c \
	src/client/ui/state/ui_load_movies.c \
	src/client/ui/state/ui_map_count_by_game_type.c \
	src/client/ui/state/ui_owner_draw_visible.c \
	src/client/ui/state/ui_owner_draw_width.c \
	src/client/ui/state/ui_owner_draw.c \
	src/client/ui/state/ui_run_menu_script.c \
	src/client/ui/state/ui_select_current_game_type.c \
	src/client/ui/state/ui_select_current_map.c \
	src/client/ui/state/ui_selected_map.c \
	src/client/ui/state/ui_sort_server_status_info.c \
	src/client/ui/state/ui_update.c \
	src/client/ui/state/ui_validate_map_preview_selection.c \
	src/client/ui/state/ui_verify_language.c
