#include "com_config.h"

#include "filesystem/filesystem.h"
#include "q_command.h"
#include "q_cvar.h"
#include "q_path.h"
#include "q_string.h"

#include <stdint.h>

static const char comGeneratedConfigHeader[] =
    "// generated by Call of Duty, do not modify\n";

#if defined(WINDOWS_BEHAVIOR)
static const char comAutomaticConfigName[] = "uoconfig_mp.cfg";
#else
static const char comAutomaticConfigName[] = "uoconfig_mp_server.cfg";
#endif

void Com_Printf(const char *format, ...);
void Key_WriteBindings(int32_t fileHandle);

/*
 * Complete common configuration-writing subsystem.  The original Windows
 * client and Linux dedicated engine retain the same decisions and call order:
 *
 *   CoDUOMP.exe   0x0043c260..0x0043c4b0
 *   coduo_lnxded  0x08071b45..0x08071d2f
 *
 * The same-module Mac client exports the canonical function names.  The one
 * target behavior difference is the automatically written filename: Windows
 * uses uoconfig_mp.cfg, while the Linux dedicated server uses
 * uoconfig_mp_server.cfg.  The explicit writeconfig and writedefaults commands
 * use their supplied filename identically on both targets.
 */

/* Source: CoDUOMP.exe 0x0043c260..0x0043c2a2; coduo_lnxded
 * 0x08071b45..0x08071ba9. Exact same-module Mac symbol:
 * Com_WriteConfigToFile. */
void Com_WriteConfigToFile(const char *filename)
{
    const int32_t fileHandle = FS_FOpenFileWrite(filename);
    if (fileHandle == 0) {
        Com_Printf("Couldn't write %s.\n", filename);
        return;
    }

    FS_Printf(fileHandle, comGeneratedConfigHeader);
    Key_WriteBindings(fileHandle);
    Cvar_WriteVariables(fileHandle);
    FS_FCloseFile(fileHandle);
}

/* Source: CoDUOMP.exe 0x0043c2b0..0x0043c2ec; coduo_lnxded
 * 0x08071baa..0x08071c03. Exact same-module Mac symbol:
 * Com_WriteDefaultsToFile. Defaults contain cvars only; the regular config
 * writer above additionally writes bindings. */
void Com_WriteDefaultsToFile(const char *filename)
{
    const int32_t fileHandle = FS_FOpenFileWrite(filename);
    if (fileHandle == 0) {
        Com_Printf("Couldn't write %s.\n", filename);
        return;
    }

    FS_Printf(fileHandle, comGeneratedConfigHeader);
    Cvar_WriteDefaults(fileHandle);
    FS_FCloseFile(fileHandle);
}

/* Source: CoDUOMP.exe 0x0043c2f0..0x0043c313; coduo_lnxded
 * 0x08071c04..0x08071c37. Exact same-module Mac symbol:
 * Com_WriteConfiguration. The Windows optimizer also inlines this helper at
 * the start of Com_Frame. */
void Com_WriteConfiguration(void)
{
    if (com_configAutowriteEnabled == qfalse) {
        return;
    }
    if ((cvar_modifiedFlags & CVAR_ARCHIVE) == 0) {
        return;
    }

    cvar_modifiedFlags &= ~(uint32_t)CVAR_ARCHIVE;
    Com_WriteConfigToFile(comAutomaticConfigName);
}

/* Source: CoDUOMP.exe 0x0043c320..0x0043c3e6; coduo_lnxded
 * 0x08071c38..0x08071cb3. Exact same-module Mac symbol: Com_WriteConfig_f.
 * The Windows compiler inlined Com_WriteConfigToFile into this command
 * callback. */
void Com_WriteConfig_f(void)
{
    char filename[MAX_QPATH];

    if (Cmd_Argc() != 2) {
        Com_Printf("Usage: writeconfig <filename>\n");
        return;
    }

    Q_strncpyz(filename, Cmd_Argv(1), (int32_t)sizeof(filename));
    Com_DefaultExtension(filename, (int32_t)sizeof(filename), ".cfg");
    Com_Printf("Writing %s.\n", filename);
    Com_WriteConfigToFile(filename);
}

/* Source: CoDUOMP.exe 0x0043c3f0..0x0043c4b0; coduo_lnxded
 * 0x08071cb4..0x08071d2f. Exact same-module Mac symbol:
 * Com_WriteDefaults_f. */
void Com_WriteDefaults_f(void)
{
    char filename[MAX_QPATH];

    if (Cmd_Argc() != 2) {
        Com_Printf("Usage: writedefaults <filename>\n");
        return;
    }

    Q_strncpyz(filename, Cmd_Argv(1), (int32_t)sizeof(filename));
    Com_DefaultExtension(filename, (int32_t)sizeof(filename), ".cfg");
    Com_Printf("Writing %s.\n", filename);
    Com_WriteDefaultsToFile(filename);
}
