#ifndef QCOMMON_SERVER_BROWSER_TYPES_H
#define QCOMMON_SERVER_BROWSER_TYPES_H

typedef enum lan_server_source_e {
    LAN_SERVER_SOURCE_LOCAL = 0,
    LAN_SERVER_SOURCE_GLOBAL = 1,
    LAN_SERVER_SOURCE_FAVORITES = 2
} lan_server_source_t;

enum { LAN_SERVER_SOURCE_COUNT = LAN_SERVER_SOURCE_FAVORITES + 1 };

typedef enum lan_server_sort_key_e {
    LAN_SERVER_SORT_PASSWORD = 0,
    LAN_SERVER_SORT_HARDWARE = 1,
    LAN_SERVER_SORT_HOSTNAME = 2,
    LAN_SERVER_SORT_MAPNAME = 3,
    LAN_SERVER_SORT_CLIENTS = 4,
    LAN_SERVER_SORT_GAMETYPE = 5,
    LAN_SERVER_SORT_PUNKBUSTER = 6,
    LAN_SERVER_SORT_MOD = 7,
    LAN_SERVER_SORT_PING = 8
} lan_server_sort_key_t;

#endif
