// Source: uo_cgame_mp_x86.dll 0x30034ec0..0x30034f4b
// Evidence: cgame_mp/mcode/uo_cgame_mp_x86/FUN_30034ec0_30034f4b.mcode
//
// CG_CheckPlayerstateEvents — fire the client-predicted entity events that the
// new player state records but the old one did not, so the local player sees
// its own events without waiting for the server snapshot.
//
// Name resolution: the .mcode header's guess "SP_script_vehicle" is a pure
// size match from the game_mp spawn-function corpus and is REJECTED — this
// function contains no spawn/vehicle logic. Its behavior is the canonical
// Quake3/CoD CG_CheckPlayerstateEvents: it walks the playerState event ring
// (eventIndex, events[], eventParms[] at +0x88/+0x8c/+0x9c, the same layout the
// recovered playerState_t already models with MAX_PS_EVENTS == 4), diffs the new
// vs. old state, calls the entity-event dispatcher (0x30022810, CG_EntityEvent)
// for each newly-appeared event, and records it into the predicted-event ring
// (cg_predictedEvents[16], cg_predictedEventSequence). The same-module PPC name
// bank lists CG_CheckPlayerstateEvents and CG_EntityEvent, and the machine code
// proves the mapping.
//
// Register ABI (compiler-chosen for this small helper): the new player state
// `ps` arrives in EBX (set by the caller, never written here); the old player
// state `ops` is the single stack argument at [ESP+0xc] after the two prologue
// pushes. The callee ends in a plain RET, so the caller cleans the stack — a
// cdecl-shaped single stack arg plus one register arg. Expressed below as a
// normal two-parameter C function; the EBX/stack split is an ABI detail, not
// source-level behavior.

#include "client/cgame/client_recovered.h"
#include "client/cgame/globals.h"

static qboolean cgame_compat_replayed_event_range_pending;
static int32_t cgame_compat_replayed_event_start;
static int32_t cgame_compat_replayed_event_end;

/* NOT_FROM_ORIGINAL_SOURCE: supply the event-index range generated by replaying
 * commands that were already predicted during the preceding render frame. */
void cgame_compat_set_replayed_event_range(int32_t start, int32_t end)
{
    cgame_compat_replayed_event_start = start;
    cgame_compat_replayed_event_end = end;
    cgame_compat_replayed_event_range_pending = qtrue;
}

/* NOT_FROM_ORIGINAL_SOURCE: match only replay-generated events against events
 * already presented from the preceding predicted state.  Restricting the new
 * side of the match to the replay range preserves genuinely new commands even
 * when automatic fire produces several identical event ids. */
static qboolean cgame_compat_mark_damage_reconciled_events(
    const playerState_t *ps, const playerState_t *ops,
    int32_t replayStart, int32_t replayEnd,
    qboolean reconciledEvents[MAX_PS_EVENTS])
{
    if (ps->damageEvent == ops->damageEvent || replayStart >= replayEnd ||
        replayEnd > ps->eventIndex) {
        return qfalse;
    }

    int32_t oldStart = coduo_int32_from_bits(
        (uint32_t)ops->eventIndex - (uint32_t)MAX_PS_EVENTS);
    int32_t newStart = coduo_int32_from_bits(
        (uint32_t)ps->eventIndex - (uint32_t)MAX_PS_EVENTS);
    int32_t oldEvents[MAX_PS_EVENTS];
    int32_t oldEventParms[MAX_PS_EVENTS];
    int32_t newEvents[MAX_PS_EVENTS];
    int32_t newEventParms[MAX_PS_EVENTS];
    qboolean oldEventValid[MAX_PS_EVENTS];
    qboolean newEventReplayed[MAX_PS_EVENTS];
    uint8_t commonSuffix[MAX_PS_EVENTS + 1][MAX_PS_EVENTS + 1] = {{0}};

    for (int32_t position = 0; position < MAX_PS_EVENTS; position++) {
        int32_t oldSequence = coduo_int32_from_bits(
            (uint32_t)oldStart + (uint32_t)position);
        int32_t newSequence = coduo_int32_from_bits(
            (uint32_t)newStart + (uint32_t)position);
        int32_t oldRing =
            (int32_t)((uint32_t)oldSequence & (MAX_PS_EVENTS - 1u));
        int32_t newRing =
            (int32_t)((uint32_t)newSequence & (MAX_PS_EVENTS - 1u));

        oldEvents[position] = ops->events[oldRing];
        oldEventParms[position] = ops->eventParms[oldRing];
        newEvents[position] = ps->events[newRing];
        newEventParms[position] = ps->eventParms[newRing];
        oldEventValid[position] =
            oldSequence >= 0 && oldSequence < ops->eventIndex;
        newEventReplayed[position] =
            newSequence >= replayStart && newSequence < replayEnd;
    }

    for (int32_t oldPosition = MAX_PS_EVENTS - 1; oldPosition >= 0;
         oldPosition--) {
        for (int32_t newPosition = MAX_PS_EVENTS - 1; newPosition >= 0;
             newPosition--) {
            if (oldEventValid[oldPosition] != qfalse &&
                newEventReplayed[newPosition] != qfalse &&
                oldEvents[oldPosition] == newEvents[newPosition] &&
                oldEventParms[oldPosition] == newEventParms[newPosition]) {
                commonSuffix[oldPosition][newPosition] =
                    (uint8_t)(commonSuffix[oldPosition + 1][newPosition + 1] + 1u);
            } else if (commonSuffix[oldPosition + 1][newPosition] >=
                       commonSuffix[oldPosition][newPosition + 1]) {
                commonSuffix[oldPosition][newPosition] =
                    commonSuffix[oldPosition + 1][newPosition];
            } else {
                commonSuffix[oldPosition][newPosition] =
                    commonSuffix[oldPosition][newPosition + 1];
            }
        }
    }

    int32_t oldPosition = 0;
    int32_t newPosition = 0;
    qboolean matchedEvent = qfalse;
    while (oldPosition < MAX_PS_EVENTS && newPosition < MAX_PS_EVENTS) {
        if (oldEventValid[oldPosition] != qfalse &&
            newEventReplayed[newPosition] != qfalse &&
            oldEvents[oldPosition] == newEvents[newPosition] &&
            oldEventParms[oldPosition] == newEventParms[newPosition] &&
            commonSuffix[oldPosition][newPosition] ==
                commonSuffix[oldPosition + 1][newPosition + 1] + 1u) {
            reconciledEvents[newPosition] = qtrue;
            matchedEvent = qtrue;
            oldPosition++;
            newPosition++;
        } else if (commonSuffix[oldPosition + 1][newPosition] >=
                   commonSuffix[oldPosition][newPosition + 1]) {
            oldPosition++;
        } else {
            newPosition++;
        }
    }

    return matchedEvent;
}

void CG_CheckPlayerstateEvents(playerState_t *ps, playerState_t *ops)
{
    int32_t newEventStart = coduo_int32_from_bits(
        (uint32_t)ps->eventIndex - (uint32_t)MAX_PS_EVENTS);
    qboolean reconciledEvents[MAX_PS_EVENTS] = {qfalse};
    qboolean replayRangePending = cgame_compat_replayed_event_range_pending;
    int32_t replayStart = cgame_compat_replayed_event_start;
    int32_t replayEnd = cgame_compat_replayed_event_end;
    int32_t eventAdvance = coduo_int32_from_bits(
        (uint32_t)ps->eventIndex - (uint32_t)ops->eventIndex);
    int32_t presentedEventCount = 0;
    int32_t suppressedEventCount = 0;

    cgame_compat_replayed_event_range_pending = qfalse;

    /* ORIGINAL_BINARY_BUG: a newly received server EV_PAIN precedes any still-
     * unacknowledged commands replayed from that snapshot.  It shifts their
     * predictable events to different sequence slots, and the retail slot
     * comparison presents their effects again.  The pain entry itself can be
     * pushed out of the four-event ring under high latency, so use the replay
     * provenance captured by prediction rather than searching for EV_PAIN. */
    if (replayRangePending != qfalse) {
        (void)cgame_compat_mark_damage_reconciled_events(
            ps, ops, replayStart, replayEnd, reconciledEvents);
    }

    // for (i = ps->eventIndex - MAX_PS_EVENTS; i < ps->eventIndex; i++)
    //   0x30034ec1 EAX = ps->eventIndex; 0x30034ecd ESI = EAX - 4 (MAX_PS_EVENTS);
    //   0x30034ed0 CMP ESI,EAX / JGE exit is the signed loop-entry test i < eventIndex;
    //   0x30034f41 INC ESI / 0x30034f42 CMP / JL is the signed loop-continue test.
    int32_t i = coduo_int32_from_bits(
        (uint32_t)ps->eventIndex - (uint32_t)MAX_PS_EVENTS);
    while (i < ps->eventIndex) {
        int32_t event;

        // 0x30034ed5 EAX = ops->eventIndex; CMP ESI,EAX / JGE process:
        // events with i >= ops->eventIndex are always new -> always processed.
        if (i < ops->eventIndex) {
            // 0x30034edf EAX = ops->eventIndex - MAX_PS_EVENTS; CMP ESI,EAX / JLE skip:
            // events older than the old state's ring window are dropped.
            int32_t oldestRetained = coduo_int32_from_bits(
                (uint32_t)ops->eventIndex - (uint32_t)MAX_PS_EVENTS);
            if (i <= oldestRetained) {
                goto next_event;
            }
            // 0x30034ef2/0x30034ef5 compare the two rings at (i & 3); JZ skip:
            // an unchanged slot is not a new event.
            int32_t compareRing =
                (int32_t)((uint32_t)i & (MAX_PS_EVENTS - 1u));
            if (ps->events[compareRing] == ops->events[compareRing]) {
                goto next_event;
            }
        }

        // 0x30034eff EDI = ps->events[i & 3]; 0x30034f06 EDX = ps->eventParms[i & 3].
        int32_t ring =
            (int32_t)((uint32_t)i & (MAX_PS_EVENTS - 1u));
        event = ps->events[ring];

        int32_t reconciliationSlot = coduo_int32_from_bits(
            (uint32_t)i - (uint32_t)newEventStart);
        if (reconciledEvents[reconciliationSlot] != qfalse) {
            cg_predictedEvents[(int32_t)((uint32_t)i &
                (MAX_PREDICTED_EVENTS - 1u))] = event;
            suppressedEventCount++;
            goto next_event;
        }

        // 0x30034f16 store eventParm into the predicted-event entity's
        // currentState.eventParm slot (+0xa4, aliased in centity_t as fxId)
        // BEFORE dispatch; 0x30034f0d..0x30034f1c call CG_EntityEvent(self=ECX, event=EAX,
        // predicted=1 on the stack).
        cg_predictedEventEntity.currentState.eventParm = ps->eventParms[ring];
        /* NOT_FROM_ORIGINAL_SOURCE: validate this recovered client-module boundary input and state before use. */
        CG_EntityEvent(&cg_predictedEventEntity, event, 1);

        // 0x30034f23/0x30034f26 cg_predictedEvents[i & 0xf] = event;
        cg_predictedEvents[(int32_t)((uint32_t)i & (MAX_PREDICTED_EVENTS - 1u))] = event;

        // 0x30034f2d..0x30034f36 cg_predictedEventSequence++;
        cg_predictedEventSequence = coduo_int32_from_bits(
            (uint32_t)cg_predictedEventSequence + 1u);
        presentedEventCount++;

next_event:
        /* INC ESI and INC EAX are target dword operations; retain their
         * modulo-2^32 behavior rather than invoking signed-overflow UB. */
        i = coduo_int32_from_bits((uint32_t)i + 1u);
    }

    /* If a server event was already pushed out of the four-slot ring, advance
     * the presentation sequence without fabricating an effect for it. */
    if (suppressedEventCount != 0 && eventAdvance > presentedEventCount) {
        cg_predictedEventSequence = coduo_int32_from_bits(
            (uint32_t)cg_predictedEventSequence +
            (uint32_t)(eventAdvance - presentedEventCount));
    }
}
